# Site
name: 'EquiGrid'
description: 'EquiGrid is a private blog devoted to the idea that data analysis and data modeling can significantly improve the planning of electric grids, facilitate the green transition, minimize losses, and enhance dealing with transient, difficult situations.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: '' #'https://github.com/szostakb/szostakb.github.io'
disqus: ''
email: '/f/mwkgknbd'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Bart:
      name:           Bart
      site:           https://szostakb.github.io/
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi! I'm Bart. I'm a data-scientist and phisicist. For years, I have been gathering knowledge, gaining experience, and acquiring new skills with the aim to help improve transmission of electricity, particularly in the context of the green transtion."
      email:          bartoszszostak22@gmail.com
      facebook:       https://szostakb.github.io/
      # twitter:        https://twitter.com/wowthemesnet

    # jane:
    #   name:           Jane
    #   site:           https://www.wowthemes.net
    #   avatar:         /assets/images/avatar2.jpg
    #   bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
    #   email:          fakemail@gmail.com
    #   twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]